version: '3'
services:
  database:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\joao.g.ferreira\Documents\Desenvolvimento\Docker\Volumes\MySql:\var\lin\mysql
